# Generated by Django 3.2.4 on 2021-07-02 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_correlation_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='correlation',
            constraint=models.UniqueConstraint(fields=('code1', 'code2', 'created_at'), name='unique_corr'),
        ),
    ]
