# Generated by Django 3.2.4 on 2021-06-20 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='correlation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiLink1', models.CharField(max_length=100)),
                ('name1', models.CharField(max_length=50)),
                ('apiLink2', models.CharField(max_length=100)),
                ('name2', models.CharField(max_length=50)),
                ('correlationVal', models.DecimalField(decimal_places=2, max_digits=3)),
                ('lastUpdated', models.DateField(auto_now=True)),
            ],
        ),
    ]
