# Generated by Django 3.2.4 on 2021-06-20 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correlation',
            name='lastUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
