# Generated by Django 3.2.4 on 2021-06-20 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_correlation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correlation',
            name='user',
        ),
    ]
