# Generated by Django 3.1.7 on 2021-06-27 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_correlation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correlation',
            name='correlationVal',
        ),
        migrations.AlterField(
            model_name='correlation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
